<a href="https://colab.research.google.com/github/vishnu-meera/ipynb-files/blob/main/loop.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
import numpy as np

def dotProduct(x,y):
  if not (isinstance(x, np.ndarray) and isinstance(y, np.ndarray)):
    raise Exception(f'{x} and {y} needs to be numpy.ndarray')

  if len(x) != len(y):
    raise Exception(f'{x} and {y} length needs to be equal')

  return np.dot(x,y)

x = np.array([1,2,4])
y = np.array([2,3,4])

dotProduct(x,y)

np.int64(24)

In [14]:
for i in range(6):
  print(i)

0
1
2
3
4
5


In [15]:
for i in range(6,11):
  print(i)

6
7
8
9
10


In [31]:
def fibnocci(n, memo={}):
    if n == 0:
      return 0
    elif n == 1:
      return 1
    elif n in memo:
      return memo[n]
    else:
      memo[n] = fibnocci(n-1) + fibnocci(n-2)
      return memo[n]
fibnocci(7)



13

In [51]:
def fib_list(n):
  lis = [0,1]
  if n < 0:
    raise Exception(f'incorrect n')
  if n == 0:
    return lis[0]
  elif n == 1:
    return lis[1]
  else:
    for i in range(2,n+1):
      lis.append(lis[i-1] + lis[i-2])
    return lis

fib_list(10)

[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55]

In [55]:
ns = np.linspace(-5,5,7)

for i in range(len(ns)):
  print(f'Index of {str(i)} has a value of {str(ns[i])}')

for i,n in enumerate(ns):
  print(f'Index of {str(i)} has a value of {str(n)}')

Index of 0 has a value of -5.0
Index of 1 has a value of -3.333333333333333
Index of 2 has a value of -1.6666666666666665
Index of 3 has a value of 0.0
Index of 4 has a value of 1.666666666666667
Index of 5 has a value of 3.333333333333334
Index of 6 has a value of 5.0
Index of 0 has a value of -5.0
Index of 1 has a value of -3.333333333333333
Index of 2 has a value of -1.6666666666666665
Index of 3 has a value of 0.0
Index of 4 has a value of 1.666666666666667
Index of 5 has a value of 3.333333333333334
Index of 6 has a value of 5.0


In [56]:
names = ['alpha', 'beta', 'gamma']
values = [10,20,30]
d = {}
for key, value in zip(names, values):
  d[key] = value

d

{'alpha': 10, 'beta': 20, 'gamma': 30}

In [57]:
z = dict(zip(names, values))
z

{'alpha': 10, 'beta': 20, 'gamma': 30}

In [63]:
from time import perf_counter as pc
N = 10000

start = pc()
m = np.zeros(N)
for i in range(N):
  m[i] = i**2
stop = pc()
print(f'time taken {(stop - start)*1000}')


start = pc()
n = np.full(N,0)
for i in range(N):
  n[i] = i**2
stop = pc()
print(f'time taken {(stop - start)*1000}')

start = pc()
o = np.array([])
for i in range(N):
  o = np.append(o,i**2)
stop = pc()
print(f'time taken {(stop - start)*1000}')

start = pc()
p = []
for i in range(N):
  p.append(i**2)
stop = pc()
print(f'time taken {(stop - start)*1000}')

time taken 3.078267000091728
time taken 2.2835390000182088
time taken 48.59307799961243
time taken 1.573129999997036


In [65]:
lists = [i**2 for i in range(10)]
lists

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [71]:
text = ['Promising', 'Yves', 'that', 'home', 'on', 'Nobb']

[word[0] for _,word in enumerate(text)]

['P', 'Y', 't', 'h', 'o', 'N']

In [85]:
['Odd' if i%2 ==1 else i for i in range(10)]

[0, 'Odd', 2, 'Odd', 4, 'Odd', 6, 'Odd', 8, 'Odd']

In [86]:
def linspace(start,stop,number):
  return [start + i * ((stop-start)/(number-1)) for i in range(number)]

x1 = linspace(-3,3,11)
y1 = [x**2 for x in x1]
print(x1)
print(y1)

[-3.0, -2.4, -1.8, -1.2000000000000002, -0.6000000000000001, 0.0, 0.5999999999999996, 1.2000000000000002, 1.7999999999999998, 2.3999999999999995, 3.0]
[9.0, 5.76, 3.24, 1.4400000000000004, 0.3600000000000001, 0.0, 0.3599999999999996, 1.4400000000000004, 3.2399999999999993, 5.759999999999997, 9.0]


In [104]:
def poissonCounter(l):
  target = np.exp(-l)
  curValue, counter = 1,0
  while curValue > target:
    counter = counter + 1
    curValue = curValue * np.random.rand()
  return counter

poissonCounter(10)

1

In [115]:
X = np.array([ [1,2,4],
               [2,3,4],
               [2,3,2],
               [4,5,6]])

w = [10,20,30]

print(X)
print('  ')
print(w)
print(X.size)
print(X.shape[0])

print(X+w)

v = np.array([-1,0,1,0], ndmin=2).T #broadcasting
print(X*v)

[[1 2 4]
 [2 3 4]
 [2 3 2]
 [4 5 6]]
  
[10, 20, 30]
12
4
[[11 22 34]
 [12 23 34]
 [12 23 32]
 [14 25 36]]
[[-1 -2 -4]
 [ 0  0  0]
 [ 2  3  2]
 [ 0  0  0]]


In [6]:

alphabet = "abcdefghijklmnopqrstuvwxyz"
for i in range(len(alphabet)):
  position = i+1
  if (position == 1):
    ordind = 'st'
  elif (position == 2):
    ordind = 'nd'
  elif (position== 3):
    ordind = 'rd'
  else:
    ordind = 'th'
  print(f'{alphabet[i]} is the {position}{ordind} letter')


a is the 1st letter
b is the 2nd letter
c is the 3rd letter
d is the 4th letter
e is the 5th letter
f is the 6th letter
g is the 7th letter
h is the 8th letter
i is the 9th letter
j is the 10th letter
k is the 11th letter
l is the 12th letter
m is the 13th letter
n is the 14th letter
o is the 15th letter
p is the 16th letter
q is the 17th letter
r is the 18th letter
s is the 19th letter
t is the 20th letter
u is the 21th letter
v is the 22th letter
w is the 23th letter
x is the 24th letter
y is the 25th letter
z is the 26th letter
